apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgis
spec:
  selector:
    matchLabels:
      app: postgis
  template:
    metadata:
      labels:
        app: postgis
    spec:
      containers:
      - name: postgis
        image: postgis/postgis
        env:
        - name: POSTGRES_PASSWORD
          value: postgres
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgis
spec:
  selector:
    app: postgis
  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432
